# Generated by Django 4.0.5 on 2022-06-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=60)),
                ('temp', models.CharField(max_length=60)),
                ('humidity', models.CharField(max_length=60)),
                ('main', models.CharField(max_length=60)),
                ('icon', models.CharField(max_length=60)),
            ],
        ),
    ]
