# Generated by Django 4.0.5 on 2022-06-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_weather_city_alter_weather_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='city',
        ),
        migrations.AddField(
            model_name='weather',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='weather',
            name='country_code',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='weather',
            name='icon',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='weather',
            name='main',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp',
            field=models.CharField(default='', max_length=60),
        ),
    ]
