# Generated by Django 4.0.5 on 2022-06-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_weather_city_weather_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='country_code',
            new_name='country',
        ),
    ]
