# Generated by Django 4.0.5 on 2022-07-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_country_code_weather_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=60)),
                ('hotel', models.CharField(default='', max_length=60)),
                ('street', models.CharField(default='', max_length=60)),
                ('country', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
