# Generated by Django 4.0.5 on 2022-07-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_country_code_weather_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('country', models.CharField(default='', max_length=60)),
                ('lon', models.CharField(default='', max_length=60)),
                ('lat', models.CharField(default='', max_length=60)),
                ('radius', models.CharField(default='', max_length=60)),
                ('kinds', models.CharField(default='', max_length=60)),
                ('rate', models.CharField(default='', max_length=60)),
                ('xid', models.CharField(default='', max_length=60)),
                ('wikipedia', models.CharField(default='', max_length=60)),
                ('image', models.CharField(default='', max_length=60)),
                ('description', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
