# Generated by Django 4.0.5 on 2022-07-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_attractions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractions',
            name='description',
        ),
        migrations.RemoveField(
            model_name='attractions',
            name='image',
        ),
        migrations.RemoveField(
            model_name='attractions',
            name='kinds',
        ),
        migrations.RemoveField(
            model_name='attractions',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='attractions',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='attractions',
            name='radius',
        ),
        migrations.RemoveField(
            model_name='attractions',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='attractions',
            name='wikipedia',
        ),
        migrations.RemoveField(
            model_name='attractions',
            name='xid',
        ),
        migrations.AddField(
            model_name='attractions',
            name='attraction_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='attractions',
            name='google_url',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='attractions',
            name='photo',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='attractions',
            name='place_id',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='attractions',
            name='rating',
            field=models.CharField(default='', max_length=60),
        ),
    ]
