# Generated by Django 4.0.5 on 2022-07-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_hotels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='country',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='street',
            field=models.CharField(default='', max_length=240),
        ),
    ]
