# Generated by Django 4.0.5 on 2022-07-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_hotels_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='imgs',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hotels',
            name='landmarks',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='country',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='street',
            field=models.CharField(default='', max_length=250),
        ),
    ]
