# Generated by Django 4.0.5 on 2022-07-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_attractions_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='attraction_names',
            field=models.JSONField(default=''),
        ),
    ]
