# Generated by Django 4.0.5 on 2022-07-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_hotels_imgs_hotels_landmarks_alter_hotels_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='prices',
            field=models.CharField(default='', max_length=250),
        ),
    ]
