# Generated by Django 4.0.5 on 2022-07-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_name_attractions_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=60)),
                ('name', models.CharField(default='', max_length=60)),
                ('time', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
