# Generated by Django 4.0.5 on 2022-08-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_hotels_prices'),
        ('api', '0016_itinerary'),
    ]

    operations = [
    ]
